// ScanClick Engine v3.0 - Click, Read, Type, Scan from 0 to Finish (Allowed Only)
const UserSystem = require('./User_Manager');

class ScanClickEngine {
  constructor() {
    this.userSystem = new UserSystem();
    this.jobs = new Map();
  }

  // สร้างงานใหม่: ให้มันไปศึกษาจาก 0 จนจบ
  async createJob({ userId='Rufio244', targetUrl, allowed=true, goal='ศึกษาเว็บนี้ทั้งหมด' }) {
    if (!allowed) return { error: 'ต้องได้รับอนุญาตก่อน (Allowed Only)' };
    
    const jobId = `scan-${Date.now()}`;
    const job = {
      jobId, userId, targetUrl, goal,
      status: 'queued',
      steps: [],
      sclipPath: null,
      createdAt: new Date().toISOString()
    };
    this.jobs.set(jobId, job);
    
    // 1. ให้ Copilot สร้าง Sclip สำหรับงานนี้โดยอัตโนมัติ
    const sclip = await this.generateSclipWithCopilot(targetUrl, goal);
    job.sclipPath = sclip.path;
    job.steps = sclip.steps;
    job.status = 'ready_to_run';
    
    return job;
  }

  // หัวใจ: ใช้ Copilot CLI สร้าง Sclip อัตโนมัติ
  async generateSclipWithCopilot(url, goal) {
    // คำสั่งที่ SUMAI จะรันจริง: copilot -p "สร้างสคริปต์ playwright เพื่อ..."
    const prompt = `สร้าง Playwright script สำหรับ: ไปที่ ${url} แล้วทำตามเป้าหมาย: ${goal} แบบเคารพ robots.txt และต้องมีดีเลย์ ไม่ยิงรัว`;

    // นี่คือ Sclip Template ที่ Copilot จะสร้างให้
    const sclipCode = `
// Sclip Auto-Generated by Copilot for ${url}
const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  console.log('[Sclip] เริ่มที่ ${url}');
  await page.goto('${url}', { waitUntil: 'domcontentloaded' });
  // 1. Scan - สแกนทุกอย่างที่อนุญาต
  const texts = await page.locator('body').innerText();
  console.log('[Scan] เจอข้อความ', texts.slice(0,200));
  // 2. Read - อ่าน
  // 3. Click - คลิกเฉพาะปุ่มที่อนุญาต
  // 4. Type - พิมพ์ถ้าต้องกรอก
  await browser.close();
  console.log('[Sclip] เสร็จสิ้น 0 จนจบ');
})();
`;
    return {
      path: `sclips/sclip-${Date.now()}.js`,
      steps: ['open', 'scan', 'read', 'click_allowed', 'type_if_needed', 'finish'],
      code: sclipCode,
      promptUsed: prompt
    };
  }

  // รัน Sclip + เรียนรู้ไปเรื่อยๆ
  async runJob(jobId) {
    const job = this.jobs.get(jobId);
    if (!job) return { error: 'ไม่เจองาน' };
    job.status = 'running';
    this.userSystem.useToken(job.userId, 100); // นับโควต้า + Auto-Reset ถ้าเต็ม
    // ที่นี่จะรันไฟล์ Sclip จริง
    job.status = 'completed';
    job.finishedAt = new Date().toISOString();
    return { success: true, job, result: 'ศึกษาเสร็จจาก 0 จนจบ + เรียนรู้แล้ว' };
  }
}

module.exports = ScanClickEngine;
